name: Acceptance Tests (minikube)

on:
  workflow_dispatch:
    inputs:
      minikubeVersion:
        description: The Minikube version
        default: latest
      runTests:
        description: The regex passed to the -run option of `go test`
        default: "^TestAccKubernetesStorageClassV1"
      terraformVersion:
        description: Terraform version
        default: 1.15.9
      parallelRuns:
        description: The maximum number of tests to run simultaneously
        default: 1
  pull_request:
    branches:
      - main
      - v3-major-release
    paths:
      - 'kubernetes/*.go'
      - 'internal/framework/**/*.go'
      - 'internal/mux/**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'GNUmakefile'
      - '.github/workflows/acceptance_tests_kind.yaml'
  schedule:
    - cron: '0 21 * * *'

env:
  KUBECONFIG: ${{ github.workspace }}/.kube/config
  MINIKUBE_VERSION: ${{ github.event.inputs.minikubeVersion || 'latest' }}
  PARALLEL_RUNS: ${{ github.event.inputs.parallelRuns || '1' }}
  TERRAFORM_VERSION: ${{ github.event.inputs.terraformVersion || '1.15.9' }} 
  
jobs:
  acceptance_tests_kind:
    runs-on: ubuntu-latest
    strategy:
      # Don't cancel all in-progress and queued jobs in the matrix if any job in the matrix fails.
      # That will be helpful to catch any issues related to a particular Kubernetes version.
      fail-fast: false
      matrix:
        kubernetes_version:
          - v1.34.0
          - v1.33.4
          - v1.32.8
          - v1.31.12
        isMajorReleaseBranch:
          - ${{ contains(github.ref, 'v3-major-release') }}
        isBaseMajorRelease:
          - ${{ contains(github.base_ref, 'v3-major-release') }}
        include:
          # include if reference is v3-major-release and base reference is not v3-major-release
          - isMajorReleaseBranch: true
            isBaseMajorRelease: false
            kubernetes_version: v1.31.4
          # include if reference is not v3-major-release and base reference is v3-major-release
          - isMajorReleaseBranch: false
            isBaseMajorRelease: true
            kubernetes_version: v1.31.4
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      - name: Create kubeconfig directory
        run: mkdir -p "$(dirname "$KUBECONFIG")"
      - name: Setup Minikube
        uses: medyagh/setup-minikube@e3c7f79eb1e997eabccc536a6cf318a2b0fe19d9 # v0.0.20
        with:
          minikube-version: ${{ env.MINIKUBE_VERSION }}
          kubernetes-version: ${{ matrix.kubernetes_version }}
          mount-path: ${{ github.workspace }}/.github/config/seccomp-profiles:/var/lib/kubelet/seccomp/profiles
      - name: Run Acceptance Test Suite
        env:
          KUBE_CONFIG_PATH: ${{ env.KUBECONFIG }}
          TESTARGS: -run ${{ github.event.inputs.runTests || '^TestAcc' }}
          # Do not set TF_ACC_TERRAFORM_PATH or TF_ACC_TERRAFORM_VERSION.
          # In this case, the framework will search for the Terraform CLI binary based on the operating system PATH.
          # Eventually, it will use the one we set up.
          # More information: https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests#terraform-cli-installation-behaviors
        run: |
          make testacc
          make frameworkacc
